### ISSUE TITLE
🐛 bug(condition): Test 2

### ISSUE THREAD

**Issue by TGTGamer** [Resnovas/smartcloud#473]
### Console Logs

```
insert debug output here
```

## Device Information

- Version: [e.g. 22]
- Platform: [e.g. macOS, Google Cloud, ubuntu 18.04]
- Browser: [e.g. stock browser, safari]
- Node Version: [e.g. v16.8.0]
- Yarn Version: [e.g. v1.22.4]
- Docker Version: [e.g. Docker version 19.03.12, build 48a66213fe]
- Package(s): [e.g. @resnovas/release-manager]
- URL: [e.g. https://console.smartcloud.gg/admin]

## Bug Checklist

- [ ] Have reproduced on my application version
- [ ] Have reproduced on a clean installation
- [ ] Have reproduced on a development build
- [ ] Have included logs or screenshots
- [ ] Have contacted support via the official website
- [ ] Have asked the community for guidance
- [ ] Have linked any related issues
- [ ] Bug confirmed by

**Comment by TGTGamer** [comment]
Semantic Conditions failed - Please title your issue using one of the valid options:

 Types: bug, chore, opt, optimisation, style, maint, maintenance, ref, refactor, revert, dep, deprecated, removal, docs, documentation, feat, enhance, feature, enhancement, fix

 Contexts: @resnovas/workflow-mastermind, @resnovas/release-mastermind, @resnovas/label-mastermind, @resnovas/variable-mastermind, @resnovas/convention-mastermind, condition, api, util, installer, deps, deps-dev

----------

This message will be automatically updated when you make this change

**Comment by ResnovasLtd** [comment]
Semantic Conditions failed - Please title your issue using one of the valid options:

 Types: bug, chore, opt, optimisation, style, maint, maintenance, ref, refactor, revert, dep, deprecated, removal, docs, documentation, feat, enhance, feature, enhancement, fix

 Contexts: @resnovas/workflow-mastermind, @resnovas/release-mastermind, @resnovas/label-mastermind, @resnovas/variable-mastermind, @resnovas/convention-mastermind, condition, api, util, installer, deps, deps-dev

----------

This message will be automatically updated when you make this change

**Comment by TGTGamer** [comment]
Gitmoji Conditions failed - Please title your issue using one of the valid options:

 Types: ⚡️ || :zap: === Improve performance.,
🐛 || :bug: === Fix a bug.,
🚑️ || :ambulance: === Critical hotfix.,
✨ || :sparkles: === Introduce new features.,
💄 || :lipstick: === Add or update the UI and style files.,
🔒️ || :lock: === Fix security issues.,
⬇️ || :arrow_down: === Downgrade dependencies.,
⬆️ || :arrow_up: === Upgrade dependencies.,
📌 || :pushpin: === Pin dependencies to specific versions.,
📈 || :chart_with_upwards_trend: === Add or update analytics or track code.,
➕ || :heavy_plus_sign: === Add a dependency.,
➖ || :heavy_minus_sign: === Remove a dependency.,
🔧 || :wrench: === Add or update configuration files.,
🌐 || :globe_with_meridians: === Internationalization and localization.,
✏️ || :pencil2: === Fix typos.,
⏪️ || :rewind: === Revert changes.,
📦️ || :package: === Add or update compiled files or packages.,
👽️ || :alien: === Update code due to external API changes.,
💥 || :boom: === Introduce breaking changes.,
🍱 || :bento: === Add or update assets.,
♿️ || :wheelchair: === Improve accessibility.,
💬 || :speech_balloon: === Add or update text and literals.,
🗃️ || :card_file_box: === Perform database related changes.,
🚸 || :children_crossing: === Improve user experience / usability.,
📱 || :iphone: === Work on responsive design.,
🥚 || :egg: === Add or update an easter egg.,
⚗️ || :alembic: === Perform experiments.,
🔍️ || :mag: === Improve SEO.,
🏷️ || :label: === Add or update types.,
🚩 || :triangular_flag_on_post: === Add, update, or remove feature flags.,
🥅 || :goal_net: === Catch errors.,
💫 || :dizzy: === Add or update animations and transitions.,
🗑️ || :wastebasket: === Deprecate code that needs to be cleaned up.,
🛂 || :passport_control: === Work on code related to authorization, roles and permissions.,
🩹 || :adhesive_bandage: === Simple fix for a non-critical issue.,
👔 || :necktie: === Add or update business logic.

For more information on gitmoji, please visit https://gitmoji.dev/

----------

This message will be automatically updated when you make this change

**Comment by ResnovasLtd** [comment]
Semantic Conditions failed - Please title your issue using one of the valid options:

 Types: bug,
chore,
opt,
optimisation,
style,
maint,
maintenance,
ref,
refactor,
revert,
dep,
deprecated,
removal,
docs,
documentation,
feat,
enhance,
feature,
enhancement,
fix

 Contexts: @resnovas/workflow-mastermind,
@resnovas/release-mastermind,
@resnovas/label-mastermind,
@resnovas/variable-mastermind,
@resnovas/convention-mastermind,
condition,
api,
util,
installer,
deps,
deps-dev

For more information on Semantic Commit Messages, please see https://www.conventionalcommits.org/en/v1.0.0/

----------

This message will be automatically updated when you make this change

**Comment by TGTGamer** [comment]
SemanticEmoji Conditions failed - Please title your issue using a combination of the valid options:
Example: ":bug: fix(context): Fixing a bug in context"

Gitmoji Options: 
⚡️ || :zap: === Improve performance.,
🐛 || :bug: === Fix a bug.,
🚑️ || :ambulance: === Critical hotfix.,
✨ || :sparkles: === Introduce new features.,
💄 || :lipstick: === Add or update the UI and style files.,
🔒️ || :lock: === Fix security issues.,
⬇️ || :arrow_down: === Downgrade dependencies.,
⬆️ || :arrow_up: === Upgrade dependencies.,
📌 || :pushpin: === Pin dependencies to specific versions.,
📈 || :chart_with_upwards_trend: === Add or update analytics or track code.,
➕ || :heavy_plus_sign: === Add a dependency.,
➖ || :heavy_minus_sign: === Remove a dependency.,
🔧 || :wrench: === Add or update configuration files.,
🌐 || :globe_with_meridians: === Internationalization and localization.,
✏️ || :pencil2: === Fix typos.,
⏪️ || :rewind: === Revert changes.,
📦️ || :package: === Add or update compiled files or packages.,
👽️ || :alien: === Update code due to external API changes.,
💥 || :boom: === Introduce breaking changes.,
🍱 || :bento: === Add or update assets.,
♿️ || :wheelchair: === Improve accessibility.,
💬 || :speech_balloon: === Add or update text and literals.,
🗃️ || :card_file_box: === Perform database related changes.,
🚸 || :children_crossing: === Improve user experience / usability.,
📱 || :iphone: === Work on responsive design.,
🥚 || :egg: === Add or update an easter egg.,
⚗️ || :alembic: === Perform experiments.,
🔍️ || :mag: === Improve SEO.,
🏷️ || :label: === Add or update types.,
🚩 || :triangular_flag_on_post: === Add, update, or remove feature flags.,
🥅 || :goal_net: === Catch errors.,
💫 || :dizzy: === Add or update animations and transitions.,
🗑️ || :wastebasket: === Deprecate code that needs to be cleaned up.,
🛂 || :passport_control: === Work on code related to authorization, roles and permissions.,
🩹 || :adhesive_bandage: === Simple fix for a non-critical issue.,
👔 || :necktie: === Add or update business logic.

Semantic Options: 
bug, chore, opt, optimisation, style, maint, maintenance, ref, refactor, revert, dep, deprecated, removal, docs, documentation, feat, enhance, feature, enhancement, fix

For more information on Semantic Commit Messages, please see https://www.conventionalcommits.org/en/v1.0.0/
For more information on gitmoji, please visit https://gitmoji.dev/

----------

This message will be automatically updated when you make this change
