### ISSUE TITLE
feature(@videndum/release-mastermind): automatically achieve project cards 

### ISSUE THREAD

**Issue by TGTGamer** [Resnovas/smartcloud#70]
Automatically achieve project cards after specific period

**Comment by VidendumStudios** [comment]
Semantic Conditions failed - Please title your issue using one of the valid options:

 Types: bug, chore, opt, optimisation, style, maint, maintenance, ref, refactor, revert, dep, deprecated, removal, docs, documentation, feat, enhance, feature, enhancement, fix

 Contexts: @videndum/workflow-mastermind, @videndum/release-mastermind, @videndum/label-mastermind, @videndum/variable-mastermind, @videndum/convention-mastermind, condition, api, util, installer, deps, deps-dev

----------

This message will be automatically updated when you make this change
